### ISSUE TITLE
Don't overwrite native `Function#bind`

### ISSUE THREAD

**Issue by jdalton** [bloodyowl/craft#10]
The `Function#bind` provided by CraftJS has less features than that of [native bind](http://es5.github.com/#x15.3.4.5). As with the array methods it should be renamed (or made to be spec compliant and not overwrite native).

**Comment by jdalton** [comment]
An example of functionality missing from CraftJS' `Function#bind` is support for bound functions called as part of a `new` expression. Here is an example using Underscore.js and Backbone:

``` js
var model = Backbone.Model.extend({});
var collection = Backbone.Collection.extend({
  model : model,
  initialize : function() {
    _.bindAll(this);
  }
});

collection.add({ name : 'test' });
// => internally performs `new this.model(...)` which should work
// but now throws `Uncaught TypeError: Object [object Object] has no method 'set'`
// because Underscore will use CraftJS' Function#bind
```

**Comment by bloodyowl** [comment]
Solved by renaming it to `Function#attach`.

**Comment by jdalton** [comment]
Rock!
