### ISSUE TITLE
What kind of cross-browser compatibility does this library have?

### ISSUE THREAD

**Issue by alejandroiglesias** [bloodyowl/craft#2]
I would love to know which tested browser versions does this library works on. I would be good to specify that on the documentation/homepage.
Nice library! Cheers.

**Comment by bloodyowl** [comment]
Thanks for your interest.

So far, Unit Tests worked on : 

**IE** : 6+
**Firefox** : 3.6+
**Safari** : 4+
**Chrome** : 1+
**Opera** : 8+
**iOS** :  5+

I still have to test it on an Android browser, when that's done, I'll update the API docs.

**Comment by alejandroiglesias** [comment]
Just to let you know I ran the tests on my mobile device. Here are the results:

Android 2.2 browser: Error on String#parseJSON. Doesn't shows the number of tests passed or failed.
Firefox 17 mobile: 128 tests of 129 passed. Failed Craft.Browser.
Opera 12 mobile: 128 tests of 129 passed. Failed Craft.Browser.

You can check that at least with the emulators. There's the Android emulator and also the Opera mobile emulator, they're good tools.

**Comment by bloodyowl** [comment]
The last two are just related to the way I perform the tests. I correct that as soon as I can. About the Android issue I'll check this too.

**Comment by bloodyowl** [comment]
For the record, tests have been updated. 
The only error that remains for now comes from the `Event.stop` test (which fails in Android 2.2 native browser because of the emulation of the `click` event).
