### ISSUE TITLE
Add .gitignore to ignore .DS_Store

### ISSUE THREAD

**Issue by jdalton** [bloodyowl/craft#3]
Add a `.gitignore` file to ignore `.DS_Store` and other files.
See https://raw.github.com/bestiejs/lodash/master/.gitignore

**Comment by jdalton** [comment]
You might also dig a `.gitattributes` file:
https://raw.github.com/bestiejs/benchmark.js/master/.gitattributes

**Comment by bloodyowl** [comment]
done.
