### ISSUE TITLE
Avoid `Object.typeOf` method when not necessary

### ISSUE THREAD

**Issue by jdalton** [bloodyowl/craft#5]
I noticed in a few places you use the  `Object.typeOf` function to check things like `undefined` or `function` and you could simply use the `typeof` operator instead.

Also you might tweak the method to use `var toString = {}.toString` and check `toString.call(value)  == '[object RegExp]'`, it follows spec a bit more closely as with [Array.isArray](http://es5.github.com/#x15.4.3.2) which is crazy fast too.

**Comment by bloodyowl** [comment]
I use the local `typeOf` function to make it easier to minify. Also it looks like that an `instanceof` check is quite faster that a call of the `{}.toString`.

**Comment by jdalton** [comment]
> I use the local typeOf function to make it easier to minify.

Gzip will handle a lot of that.

> Also it looks like that an instanceof check is quite faster that a call of the {}.toString.

Yap for sure, it's a balance of compliance vs common use. The `toString.call()` will work cross-iframe and follows spec more closely, but it's up to you to frame your support.

**Comment by bloodyowl** [comment]
I keep this in mind for a next update. ;)
