### ISSUE TITLE
`fold` should support a `context` argument.

### ISSUE THREAD

**Issue by jdalton** [bloodyowl/craft#6]
As with other array methods `fold` should support a `context` argument.

**Comment by bloodyowl** [comment]
The native `[].reduce` doesn't support it, and I don't think that a `(function(){}).call` would really be useful here.

**Comment by jdalton** [comment]
Ah good point, though Underscore/Lo-Dash/Prototype.js support it and it keeps with API expectations (it seems a little wtf that this one method wouldn't allow it).
