### ISSUE TITLE
Don't overwrite native `Element#remove` if it exists

### ISSUE THREAD

**Issue by jdalton** [bloodyowl/craft#9]
I'm not a fan of extending DOM prototypes because I've seen the issues it's caused PrototypeJS.
See http://perfectionkills.com/whats-wrong-with-extending-the-dom/.

WebKit now has [DOM4 mutation method support](http://dom.spec.whatwg.org/#mutation-methods) for `append()`, `prepend()`, `before()`, `after()`, `replace()`, and `remove()`. See https://plus.google.com/u/0/113127438179392830442/posts/KLfpJKLDEsv.

I don't know if overwriting `Element#remove` will cause errors, but it's probably best to simply punt if it exists.

**Comment by bloodyowl** [comment]
Done, if finds `Element#remove`, doesn't overwrite it.

**Comment by jdalton** [comment]
Thanks for the fast fixes ;D

**Comment by bloodyowl** [comment]
You're welcome. 
Thanks by the way for pointing out these issues.
